ANC.Antecedentes-web/Controllers/ConsultaTramiteController.cs
using ANC.Entidades;
using Microsoft.AspNetCore.Mvc;
using ANC.Comun;
using ANC.Comun.Log4net;
using System.Drawing.Imaging;
using ANC.Modelo;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Security.Cryptography;
using ANC.AntecedentesWeb.UtilesPC;
using System.IO;
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace ANC.AntecedentesWeb.Controllers
{
    public class ConsultaTramiteController : Controller
    {
        GenericoModel genericoModel = new GenericoModel();
        AntecedentesModel _antecedentesModel = new AntecedentesModel();
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly JwtManager _jwtManager;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public ConsultaTramiteController(IConfiguration configuration, IWebHostEnvironment hostEnvironment, JwtManager jwtManager, IHttpContextAccessor httpContextAccessor)
        {
            _configuration = configuration;
            _hostEnvironment = hostEnvironment;
            _jwtManager = jwtManager;
            _httpContextAccessor = httpContextAccessor;
        }
        public async Task<IActionResult> ConsultaTramite()
        {

            List<PetTipoDocBE> lstTipoDoc = await genericoModel.ObtenerTipoDoc();
            ViewBag.lstTipoDoc = lstTipoDoc;
            List<ListAnioBE> lstAnio= await _antecedentesModel.ListarAnio();
            ViewBag.lstAnio = lstAnio;


            return View();
        }


        [HttpPost]
        public async Task<IActionResult> ConsultarRegistro([FromBody] ConsultaAntecedenteBE datos)
        {

            SesionAntecedentesBE SessionBE = new SesionAntecedentesBE();
            var userAgent = _httpContextAccessor.HttpContext.Request.Headers["User-Agent"].ToString();

            // Asigna el sistema operativo a tu objeto SessionBE
            SessionBE.sistema_operativo = Util.GetOperatingSystem(userAgent);

            Util util = new Util(_httpContextAccessor);
            SessionBE.direccion_ip = util.GetIPAddress();
            SessionBE.mac_address = Util.GetMACAddress();
            SessionBE.computer_name = Environment.MachineName;
            RptBE rpta = new RptBE();
            try
            {

                int longitudClaveBytes = 32;

                // Generar la clave aleatoria
                byte[] claveAleatoria = GenerarClaveAleatoria(longitudClaveBytes);

                // Convertir la clave aleatoria a una cadena hexadecimal para su fácil visualización
                string claveAleatoriaHex = BitConverter.ToString(claveAleatoria).Replace("-", "");

                HttpContext.Session.Remove("ssgenerico");

                HttpContext.Session.SetString("ssgenerico", claveAleatoriaHex);


                char tipo_consulta = datos.nro_registro[0]; // Accede al primer carácter de la cadena
          
                tipo_consulta = char.ToUpper(tipo_consulta); // Opcional: convertir a mayúscula

                datos.tipo_consulta = (tipo_consulta.ToString() == "C") ?1:2;
                datos.nro_registro = datos.nro_registro.Substring(1);

                if (datos.nro_registro == "000000")
                {
                    rpta.codigo = -1;
                    rpta.valor = "El numero de Trámite no puede ser 0";
                    return Json(rpta, new Newtonsoft.Json.JsonSerializerSettings());
                }

                if (HttpContext.Session.GetString("CaptchaImageText").ToUpper() == datos.textCaptcha.ToUpper())
                {

                    paramsApiReniec reniec = new paramsApiReniec();
                    reniec.cod_distrito = 50;
                    reniec.modulo = "MOD_RENIEC_WEB";
                    reniec.datosConsulta = new RequestReniecModel
                    {
                        formatoRespuesta = "json",
                        consultante = "43719662",
                        motivo = "09998-20026/INVESTIGACION DEFINITIVA/ANCASH DE ORIGEN ANC",
                        personaConsultada = new PersonaConsultada
                        {
                            tipoConsulta = "2",
                            nroDocumentoIdentidad = datos.num_documento,

                        },
                        pagination = new Pagination
                        {
                            size = 30,
                            page = 0
                        },
                        auditoria = new AuditoriaReniecDedicada
                        {
                            usuario = "43719662",
                            nombrePc = SessionBE.computer_name,
                            direccionMac = SessionBE.mac_address,
                            numeroIp = SessionBE.direccion_ip

                        }
                    };
                    ReniecBE reniecBE = await genericoModel.ConsultarReniecDNI(reniec);



                    AntecedentesBE _datosAntecedentes = new AntecedentesBE();

                    _datosAntecedentes.num_documento = reniecBE.numdni;
                    _datosAntecedentes.ap_paterno = reniecBE.apaterno;
                    _datosAntecedentes.ap_materno = reniecBE.apaterno;
                    _datosAntecedentes.nombres = reniecBE.nombres;

                    RptVerificacionBE rptVerificacion = await _antecedentesModel.LoginVericar(_datosAntecedentes);

                    if (rptVerificacion.codigo != 0)
                    {

                        datos.cod_intper = 0;


                    }
                    else
                    {
                        datos.cod_intper = rptVerificacion.cod_intper;
                    }


                    SessionBE.cod_intper = datos.cod_intper;
                    datos.cod_tipantec = 0;

                    datos.cod_subtipantec = 0;

                    datos.cod_origantec = 0;
                    datos.fla_vigencia = 9999;


                    List<RptConsutaAntecedenteBE> rptConsultaAntecedente = await _antecedentesModel.ConsultaAntecedentes(datos);

                    if (rptConsultaAntecedente.Count > 0)
                    {
                        SessionBE.nro_registro = datos.nro_registro;
                        SessionBE.anio_td = datos.anio;
                        SessionBE.cod_intper = rptVerificacion.cod_intper;
                        SessionBE.num_documento = reniecBE.numdni;
                        SessionBE.cod_tipodoc = datos.cbTipoDocumento;

                        SessionBE.ap_paterno = reniecBE.apaterno;
                        SessionBE.ap_materno = reniecBE.amaterno;
                        SessionBE.nombres = reniecBE.nombres;

                        SessionBE.fec_emisiondoc = reniecBE.fecha_expedicion;
                        SessionBE.fec_nacimiento = reniecBE.fechanac;

                        SessionBE.coddepartamento = reniecBE.departamentonac;
                        SessionBE.codprovincia = reniecBE.provincianac;
                        SessionBE.coddistrito = reniecBE.distritonac;
                        SessionBE.telefono = "";


                        //SessionBE.correo = datos.txtEmail;
                        SessionBE.id_sesion = HttpContext.Session.GetString("ssgenerico").ToString();

                        SessionBE.cod_usuario = SessionBE.num_documento;


                        SessionBE.foto = reniecBE.foto;
                        SessionBE.cod_distrito_ftp = rptVerificacion.cod_distri;



                        //servira para saber si es registro o consulta
                        SessionBE.cod_tipmovantec = 2;
                        //agregar tipo de consulta

                        SessionBE.tipo_consulta = datos.tipo_consulta;

                        if (datos.tipo_consulta == 1)
                        {
                            SessionBE.cod_tipo_repo = rptConsultaAntecedente[0].rn_cod_tipantec;
                            SessionBE.des_tip_repo = rptConsultaAntecedente[0].rs_des_tipantec;
                            SessionBE.nro_registro = rptConsultaAntecedente[0].rs_nro_registro;
                            
                            SessionBE.anio_td = rptConsultaAntecedente[0].rs_anio;
                            SessionBE.fec_caducidad = rptConsultaAntecedente[0].rd_fec_vigencia.ToString("dd/MM/yyyy");
                            SessionBE.fec_expedido = rptConsultaAntecedente[0].rd_fec_generacion.ToString("dd/MM/yyyy");
                            SessionBE.nombre_doc = rptConsultaAntecedente[0].rs_nombre_doc;
                            SessionBE.ruta_certificado = rptConsultaAntecedente[0].rs_nombre_doc;
                            SessionBE.ruta_doc_ftp = new string[]
                              {
                                     rptConsultaAntecedente[0].rs_nombre_doc
                              };
                            SessionBE.rn_cod_antec = rptConsultaAntecedente[0].rn_cod_antec;
                            SessionBE.cod_antec = new int[] { rptConsultaAntecedente[0].rn_cod_antec };
                            SessionBE.rs_cod_antec = rptConsultaAntecedente[0].rn_cod_antec.ToString();
                            SessionBE.rn_fla_vigencia = rptConsultaAntecedente[0].rn_fla_vigencia;
                            SessionBE.rn_fla_generado = rptConsultaAntecedente[0].rn_fla_generado;
                            SessionBE.tipo_documentos = new string[]
                            {
                            (rptConsultaAntecedente[0].rn_cod_tipantec == 1) ? "CD" : "CE"
                              };
                        }
                        else
                        {


                            foreach (RptConsutaAntecedenteBE row in rptConsultaAntecedente)
                            {
                                SessionBE.cod_antec = new int[] { row.rn_cod_antec };

                            }
                            SessionBE.n_cod_intmp = rptConsultaAntecedente[0].rn_cod_intmp;

ANC.Antecedentes-web/Views/ConsultaTramite/ConsultaTramite.cshtml
@{
    ViewData["Title"] = "Consulta de Trámite CADe";
}
@using ANC.Entidades;


<div class="section-consulta-tramite text-center">
    @Html.AntiForgeryToken()
    <form class="container" id="validacion-form-consulta">
        <div class="row text-left">

            <div class="col col-md-3 form-group">
                <label>Tipo de documento:<span class="text-color">(*)</span></label>
                <select class="form-control" id="tipo_documento" name="tipo_documento">
                    
                    @foreach (PetTipoDocBE item in ViewBag.lstTipoDoc)
                    {
                        if (@item.codtipodoc == 2)
                        {
                            <option value="@item.codtipodoc">@item.descripcion</option>
                        }
                       
                    }

                </select>
            </div>
            <div class="col col-md-3 form-group">
                <label>Número de Documento:<span class="text-color">(*)</span></label>
                <input type="text" class="form-control" name="num_documento" id="num_documento" maxlength="8"  onkeypress="soloNumerosValidaVarios(this, event, 0)" required>
            </div>
            <div class="col col-md-3 form-group">
                <label>N° de Trámite:<span class="text-color">(*)</span></label>
                <input type="text" class="form-control" name="nro_registro" id="nro_registro" onkeyup="mayus(this);" maxlength="7" placeholder="C / T ------" required>
            </div>
            <div class="col col-md-3 form-group">
                <label>Año:<span class="text-color">(*)</span></label>

                <select class="form-control" id="cbanio" name="cbanio">

                    @foreach (ListAnioBE item in ViewBag.lstAnio)
                    {

                        <option value="@item.rn_anio">@item.rn_anio</option>
                        

                    }

                </select>
            </div>

        
            <div class="col col-md-3 form-group">
                <label>Captcha  <span class="text-color">(*)</span></label>
                <input type="text" class="form-control" placeholder="Ingrese Codigo Captcha" name="textCaptcha" id="textCaptcha" maxlength="5"  onkeypress="soloNumerosValidaVarios(this, event, 0)" required>
            </div>

            <div class="col col-md-3 form-group">
                <label>&nbsp;</label>
                <div style="display: flex;flex-wrap: nowrap;">

                    <div>
                        <img src="" id="imgCaptcha" width="200" height="50"/>

                    </div>
                    <div class="btn-reload">

                        <button id="id-reload" type="button" onclick="cargarCapchaImagen()"  style="position:relative"><i class="ti-reload"></i> </button>


                    </div>

                </div>
            </div>
            <div class="col col-md-12">
                <span>Todos los campos con <span class="text-color">(*)</span> son necesarios para atender correctamente su solicitud.</span>
                <div class="pt-4">
                    <button class="btn  btn-main" id="btn-registrar" type="submit"> Continuar </button>

                    <a href="@Url.Action("Index", "Home")" class="btn btn-outline-dark"> Salir </a>

                </div>





            </div>
        </div>

    </form>
</div>

@section scripts{
    <script type="text/javascript">

        var UrlAuto = {
            CargarCaptchaImage: { "link": "@Url.Action("CargarCaptchaImage", "Autenticacion")" },
            ConsultarRegistro: { "link": "@Url.Action("ConsultarRegistro", "ConsultaTramite")" }
        };
        window.onload = cargarCapchaImagen();

        function cargarCapchaImagen() {
            $.ajax({
                type: 'GET',
                url: UrlAuto.CargarCaptchaImage.link,
                async: false,
                success: function (data) {
                    if (data != null) {
                        $("#imgCaptcha").attr('src', data.valor);
                    }
                }
            });
        }

        $('#validacion-form-consulta').bootstrapValidator({
            fields: {
                tipo_documento: {
                    validators: {
                        notEmpty: {
                            message: 'Seleccione Tipo de Documento'
                        }
                    }
                },
                num_documento: {
                    validators: {
                        notEmpty: {
                            message: 'Ingrese el Numero de Documento'
                        }
                    }
                },
                nro_registro: {
                    validators: {
                        notEmpty: {
                            message: 'Ingrese el Numero de Trámite '
                        },
               
                        callback: {
                            message: 'El formato debe ser una letra seguida de 6 números',
                            callback: function (value, validator, $field) {
                               
                                if (value && value.length === 7) {
                                    var primeraLetra = value.charAt(0);
                                    var numeros = value.substring(1);
                                    var letraValida = /^[A-Za-z]$/.test(primeraLetra);
                                    var numerosValidos = /^[0-9]{6}$/.test(numeros);
                                    return letraValida && numerosValidos;
                                }

                                return false; // No cumple con el formato esperado
                            }
                        }
                    }
                },
                cbanio: {
                    validators: {
                        notEmpty: {
                            message: 'Seleccione el año de Trámite'
                        }
                    }
                },
              
                textCaptcha: {
                    validators: {
                        notEmpty: {
                            message: 'Ingrese Codigo Captcha'
                        }
                    }
                }
            }
        }).on('success.form.bv', function (e) {
            e.preventDefault();

            ConsultarDatos();

        });
        function ConsultarDatos() {
            var formData = {};
            formData.cbTipoDocumento = $("#cbTipoDocumento").val();
            formData.num_documento = $("#num_documento").val();
            formData.nro_registro = $("#nro_registro").val();
            formData.anio = $("#cbanio").val();
         
            formData.textCaptcha = $("#textCaptcha").val();




            $.ajax({
                type: 'POST',
                url: UrlAuto.ConsultarRegistro.link,
                data: JSON.stringify(formData),
                processData: false,
                contentType: 'application/json',
                beforeSend: function () {
                    $("#cargando").show();
                },
                success: function (data) {
                    debugger;
                    $("#cargando").hide();


                    if (data.redirectTo) {

                        window.location.href = data.redirectTo;
                    } else {
                        if (data.codigo != 0) {
                            alerta('A', data.valor);
                            $("#textCaptcha").val("");
                        }
                    }

                    cargarCapchaImagen();
                },
                error: function (request, status, error) {
                    $("#cargando").hide();
                    alerta('E', "Surgió un problema. " + error);
                    cargarCapchaImagen();
                    $("#textCaptcha").val("");
                }
            });
        
        
        
        }



        
        function completarConCeros(numero) {

            let letraInicial = numero.charAt(0);
            let numerosRestantes = numero.slice(1);

            let numerosCompletados = numerosRestantes.padStart(6, '0');

            let valorCompleto = letraInicial + numerosCompletados;

            return valorCompleto;
        }
        function validarFormatoRegistro(value) {
         
            if (value && value.length === 7) {

                var primeraLetra = value.charAt(0);
                var numeros = value.substring(1);

                var letraValida = /^[A-Za-z]$/.test(primeraLetra);
                var numerosValidos = /^[0-9]{6}$/.test(numeros);

                return letraValida && numerosValidos;
            }

            return false; 
        }

        let input = document.getElementById('nro_registro');


        input.addEventListener('blur', function (event) {

            let valorInput = event.target.value;

            let patron = /^[A-Za-z]\d{0,6}$/;
            if (!patron.test(valorInput)) {

                return;
            }

            let valorCompletado = completarConCeros(valorInput);

            event.target.value = valorCompletado;
         
            let esValido = validarFormatoRegistro($('#nro_registro').val())

            let bootstrapValidator = $('#validacion-form-consulta').data('bootstrapValidator');

            if (bootstrapValidator) {
                // Actualizar el estado de la validación para el campo nro_registro
                bootstrapValidator.updateStatus('nro_registro', esValido ? 'VALID' : 'INVALID');
            }
        });
    </script>
}