ANC.Antecedentes-web/Controllers/HomeController.cs
using ANC.AntecedentesWeb.Models;
using Microsoft.AspNetCore.Mvc;

using System.Diagnostics;

namespace ANC.AntecedentesWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            Salir();
            return View();
        }



        public IActionResult Error(int? statusCode)
        {
            return View("Error"); // Muestra la vista de error personalizado
        }



        public ActionResult Salir()
        {
            HttpContext.Session.SetString("ssgenerico", "");
            HttpContext.Session.SetString("ssglobal", "");
            HttpContext.Session.SetString("TokenSesion", "");

            HttpContext.Session.Remove("ssgenerico");
            HttpContext.Session.Remove("ssglobal");
            HttpContext.Session.Remove("TokenSesion");
            

            return RedirectToAction("Index", "Home");
        }

    }
}

ANC.Antecedentes-web/Controllers/PoliticasController.cs
using ANC.AntecedentesWeb.Api_Tokens;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography;

namespace ANC.AntecedentesWeb.Controllers
{
    public class PoliticasController : Controller
    {
        util _utilSession=new util();
        public IActionResult TerminosCondiciones()
        {

            int longitudClaveBytes = 32;

            // Generar la clave aleatoria
            byte[] claveAleatoria = _utilSession.GenerarClaveAleatoria(longitudClaveBytes);

            // Convertir la clave aleatoria a una cadena hexadecimal para su fácil visualización
            string claveAleatoriaHex = BitConverter.ToString(claveAleatoria).Replace("-", "");

            //Session.RemoveAll();
            HttpContext.Session.Remove("ssgenerico");

            HttpContext.Session.SetString("ssgenerico", claveAleatoriaHex);
            return View();
        }

       
    }
}

ANC.Antecedentes-web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Sistema de información disciplinario ";
}



    <div class="section-tramite text-center d-flex justify-content-center">
        <div class="d-flex flex-column">

        
        <div class="tramite-content">
            <a href="@Url.Action("TerminosCondiciones", "Politicas")" class="btn btn-large btn-solid-border mt-3 "> Nuevo Trámite </a>
        </div>
        <div class="tramite-content">
        <a href="@Url.Action("ConsultaTramite", "ConsultaTramite")" class="btn btn-large btn-solid-border mt-3 ">Acceder a Trámite Realizado</a>
        </div>
    </div>
    </div>
   