ANC.Antecedentes-web/Controllers/AutenticacionController.cs
using ANC.AntecedentesWeb.Api_Tokens;
using ANC.AntecedentesWeb.UtilesPC;
using ANC.Comun;
using ANC.Comun.Log4net;
using ANC.Entidades;
using ANC.Modelo;

using Microsoft.AspNetCore.Mvc;
using SRVTextToImage;
using System.Drawing.Imaging;
using System.Net;
using static System.Runtime.InteropServices.JavaScript.JSType;


namespace ANC.AntecedentesWeb.Controllers
{
    public class AutenticacionController : Controller
    {
        Funciones fn = new Funciones();
        GenericoModel genericoModel = new GenericoModel();
        AntecedentesModel _antecedentesModel = new AntecedentesModel();

        util _utilSession = new util();

        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly JwtManager _jwtManager;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private static string correo_copia_uti = "", estado_envio = "";
        public AutenticacionController(IConfiguration configuration, IWebHostEnvironment hostEnvironment, JwtManager jwtManager, IHttpContextAccessor httpContextAccessor)
        {
            _configuration = configuration;
            _hostEnvironment = hostEnvironment;
            _jwtManager = jwtManager;
            _httpContextAccessor = httpContextAccessor;
            correo_copia_uti = _configuration.GetValue<string>("EMAIL_CORREO_UTI_COPIA");
            estado_envio = _configuration.GetValue<string>("ESTADO_ENVIO");
        }
        public ActionResult<double> GenerarTokenSesion()
        {
            if (HttpContext.Session.GetString("ssgenerico") == null)
            {
                return RedirectToAction("Salir", "Home");
            }

            var ssgenerico = HttpContext.Session.GetString("ssgenerico");

            var (token, expiresInMinutes) = _jwtManager.GenerateTokenUserID(ssgenerico);


            HttpContext.Session.SetString("TokenSesion", token);

            return expiresInMinutes;
        }

        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("ssgenerico") == null)
            {
                return RedirectToAction("Salir", "Home");
            }

         



            var tiempoRestante = GenerarTokenSesion();


            ViewBag.tiempoRestante = tiempoRestante.Value;
            List<PetTipoDocBE> lstTipoDoc = await genericoModel.ObtenerTipoDoc();
            ViewBag.lstTipoDoc = lstTipoDoc;

            List<DepartamentoBE> lstDepartamento = await genericoModel.ObtenerDepartamento();
            ViewBag.lstDepartamento = lstDepartamento;


            return View();
        }

        public async Task<ActionResult> ObtenerProvincia(string IdDepartamento)
        {
            List<ProvinciaBE> lstProvincia = await genericoModel.ObtenerProvincia(IdDepartamento);

            return Json(lstProvincia, new Newtonsoft.Json.JsonSerializerSettings());
        }
        public async Task<ActionResult> ObtenerDistrito(string IdDepartamento, string IdProvincia)
        {
            List<DistritoBE> lstDistrito = await genericoModel.ObtenerDistrito(IdDepartamento, IdProvincia);

            return Json(lstDistrito, new Newtonsoft.Json.JsonSerializerSettings());
        }

        [HttpPost]
        public async Task<IActionResult> ValidarUsuario([FromBody] TipoReporteBE data)
        {
            if (HttpContext.Session.GetString("ssgenerico") == null)
            {
                return RedirectToAction("Index", "Home");
            }


            var ssglobal = HttpContext.Session.GetString("ssglobal");
            var sesionGlobal = Newtonsoft.Json.JsonConvert.DeserializeObject<SesionAntecedentesBE>(ssglobal);

            RptBE rpta = new RptBE();
            try
            {
                var TokenSesion = HttpContext.Session.GetString("TokenSesion");

                var tiempoRestante = _jwtManager.ValidateTokenUserID(TokenSesion);

                if (tiempoRestante == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                ViewBag.tiempoRestante = tiempoRestante;


                List<int> cod_repo = new List<int>();




                if (!string.IsNullOrEmpty(data._radioTipoRepo1))
                {
                    int tip_01 = Int32.Parse(data._radioTipoRepo1);
                    cod_repo.Add(tip_01);
                }
              
                if (!string.IsNullOrEmpty(data._radioTipoRepo2))
                {
                    int tip_02 = Int32.Parse(data._radioTipoRepo2);
                    cod_repo.Add(tip_02);
                }


                int[] cod_tiprepo = cod_repo.ToArray();




                if (cod_tiprepo.Length==0)
                {
                    rpta.codigo = -1;
                    rpta.valor = "Seleccione al menos un tipo de Certificado a solicitar";
                    return Json(rpta, new Newtonsoft.Json.JsonSerializerSettings());
                }


                bool estado_verificacion = true;
                string valor_verificacion = "";
                int count = 1;
               

                sesionGlobal.cod_subtipo_repo = 1;

                sesionGlobal.cod_origantec = 1;
                sesionGlobal.nro_registro = "";

                //VALIDACION DE DATOS CON PROCEDIMIENTO 
                AntecedentesBE _datosAntecedentes = new AntecedentesBE();

                _datosAntecedentes.num_documento = sesionGlobal.num_documento;
                _datosAntecedentes.ap_paterno = sesionGlobal.ap_paterno;
                _datosAntecedentes.ap_materno = sesionGlobal.ap_materno;
                _datosAntecedentes.nombres = sesionGlobal.nombres;

                RptVerificacionBE rptVerificacion = await _antecedentesModel.LoginVericar(_datosAntecedentes);
               
               
            
               
                if (rptVerificacion.codigo != 0)
                {
                    sesionGlobal.cod_distrito_ftp = rptVerificacion.cod_distri;

                    foreach (int row in cod_tiprepo)
                    {
                        sesionGlobal.cod_tipo_repo = row;
                        string titulo_correo = (sesionGlobal.cod_tipo_repo == 1) ? "DISCIPLINARIOS" : "DE EXPEDIENTES";
                        RptVerificacionBE rptVerificacionTDAntec = await _antecedentesModel.VerificarTDAntecedente(sesionGlobal.num_documento, sesionGlobal.cod_tipo_repo);

                        if (rptVerificacionTDAntec.rn_codigo != 0)
                        {
                            estado_verificacion = false;

                            if (count == 2)
                            {
                                valor_verificacion += "; DEL MISMO MODO, " + rptVerificacionTDAntec.rs_valor + " PARA EL CERTIFICADO DE ANTECEDENTES " + titulo_correo;

                            }
                            else
                            {
                                valor_verificacion += rptVerificacionTDAntec.rs_valor + " PARA EL CERTIFICADO DE ANTECEDENTES " + titulo_correo;

                            }



                        }

                        count++;
                    }
                    if (!estado_verificacion)
                    {
                        rpta.codigo = -1;
                        rpta.valor = valor_verificacion;
                        return Json(rpta, new Newtonsoft.Json.JsonSerializerSettings());
                    }

                    //se inicializa nuevamente las variables.
                    count = 1;
                    estado_verificacion = true;
                    valor_verificacion = "";
                    foreach (int row in cod_tiprepo)
                    {

                        sesionGlobal.cod_tipo_repo = row;


                        TramiteDocumentarioBE DatosTramiteDoc = new TramiteDocumentarioBE();

                        DatosTramiteDoc.ap_paterno = sesionGlobal.ap_paterno;
                        DatosTramiteDoc.ap_materno = sesionGlobal.ap_materno;
                        DatosTramiteDoc.nombres = sesionGlobal.nombres;
                        DatosTramiteDoc.num_documento = sesionGlobal.num_documento;
                        DatosTramiteDoc.correo = sesionGlobal.correo;
                        DatosTramiteDoc.tipo_antecedente = sesionGlobal.cod_tipo_repo;
                        DatosTramiteDoc.nro_celular = sesionGlobal.telefono;
                        DatosTramiteDoc.des_departamento = sesionGlobal.des_departamento;
                        DatosTramiteDoc.des_provincia = sesionGlobal.des_provincia;
                        DatosTramiteDoc.des_distrito = sesionGlobal.des_distrito;
                        DatosTramiteDoc.firma_user = sesionGlobal.firma_reniec;
                        DatosTramiteDoc.cod_distrito_ftp = sesionGlobal.cod_distrito_ftp;
                        DatosTramiteDoc.cod_orig_antec = sesionGlobal.cod_origantec;
                        DatosTramiteDoc.usuario = "USRSYS";
                        DatosTramiteDoc.accion = "N";

                        RptTramiteDocumentarioBE RspTramiteDoc = await _antecedentesModel.RegistroTramiteDocumentario(DatosTramiteDoc);

                        if (RspTramiteDoc.rn_codigo != 0)
                        {
                            estado_verificacion = false;
                            if (count == 2)
                            {

                                valor_verificacion += " ; " + RspTramiteDoc.rs_valor;
                            }
                            else
                            {

                                valor_verificacion += RspTramiteDoc.rs_valor;

                            }

                            rpta.codigo = -1;

ANC.Antecedentes-web/Controllers/PoliticasController.cs
using ANC.AntecedentesWeb.Api_Tokens;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography;

namespace ANC.AntecedentesWeb.Controllers
{
    public class PoliticasController : Controller
    {
        util _utilSession=new util();
        public IActionResult TerminosCondiciones()
        {

            int longitudClaveBytes = 32;

            // Generar la clave aleatoria
            byte[] claveAleatoria = _utilSession.GenerarClaveAleatoria(longitudClaveBytes);

            // Convertir la clave aleatoria a una cadena hexadecimal para su fácil visualización
            string claveAleatoriaHex = BitConverter.ToString(claveAleatoria).Replace("-", "");

            //Session.RemoveAll();
            HttpContext.Session.Remove("ssgenerico");

            HttpContext.Session.SetString("ssgenerico", claveAleatoriaHex);
            return View();
        }

       
    }
}

ANC.Antecedentes-web/Views/Politicas/TerminosCondiciones.cshtml
@{
    ViewData["Title"] = "Terminos y Condiciones CADe";
}


<div class="section-TerminosCondiciones">
    <h4 class="mb-3 text-color text-uppercase text-center font-weight-bold">TÉRMINOS LEGALES Y CONDICIONES DE USO DEL
        SERVICIO DE EMISIÓN DE CERTIFICADO DE ANTECEDENTES DISCIPLINARIOS Y CERTIFICADO DE EXPEDIENTES ELECTRÓNICO</h4>


    <form id="terminosCondiciones-form" method="post">


        <div class="scroll-terminosCondiciones p-3">
            <p>Estos términos legales y condiciones de uso tienen carácter obligatorio, por lo que cualquier persona, en
                adelante “el usuario”, que decida utilizar el presente servicio, acepta su contenido y se obliga a
                cumplir los términos y condiciones de uso descritos a continuación. Si el usuario no estuviera de
                acuerdo total o parcialmente con estos términos legales y condiciones de uso, deberá abstenerse de usar
                el presente servicio.</p>

            <h4 class="text-uppercase font-weight-bold">I. Conocimiento y Aceptación de los Términos del Servicio</h4>
            <h6 class="text-uppercase">Del Alcance del Servicio</h6>
            <ol>
                <li>El servicio está disponible para todos los ciudadanos mayores de edad, ingresando su número de DNI.
                </li>
                <li>Una vez realizado el trámite, no podrá solicitar su anulación.</li>
                <li>El Certificado de Antecedentes Disciplinarios y el Certificado de Expedientes Electrónico que se
                    emiten como resultado del uso de este servicio, emplean los datos de identificación registrados en
                    la Base de Datos SISANC.</li>
                <li>El Certificado de Antecedentes Disciplinarios y el Certificado de Expedientes Electrónico tienen una
                    vigencia de 90 días calendario, contados a partir del día en que se realizó el trámite, periodo
                    dentro del cual podrá ser utilizado.</li>
                <li>El Certificado de Antecedentes Disciplinarios y el Certificado de Expedientes electrónico se
                    encontrarán disponibles para su descarga durante el periodo de su vigencia.</li>
            </ol>

            <h6 class="text-uppercase font-weight-bold">Del Trámite</h6>
            <ol>
                <li>El trámite del Certificado de Antecedentes Disciplinarios y el Certificado de Expedientes
                    electrónico es personal.</li>
                <li>Los datos declarados por el usuario se encuentran sujetos a validación.</li>
                <li>Si alguno de los datos consignados por el usuario fuera erróneo, la emisión del Certificado de
                    Antecedentes Disciplinarios y el Certificado de Expedientes electrónico será sujeto de evaluación y
                    demorará en promedio 24 horas (Trámite Observado).</li>
                <li>Si el usuario tramita su Certificado de Antecedentes Disciplinarios y/o Certificado de Expedientes
                    electrónico fuera del horario laboral y este resulta “Observado”, el Certificado se generará el
                    siguiente día hábil.</li>
            </ol>

            <h6 class="text-uppercase font-weight-bold">Del Certificado de Antecedentes Disciplinarios y el Certificado
                de Expedientes Electrónico</h6>
            <ol>
                <li>El Certificado de Antecedentes Disciplinarios y el Certificado de Expedientes son documentos en
                    formato PDF firmado digitalmente por el Poder Judicial.</li>
                <li>La validez del Certificado de Antecedentes Disciplinarios y del Certificado de Expedientes impresos
                    puede ser verificada a través de la página web del Poder Judicial, con el código inserto en la parte
                    inferior de dicho Certificado.</li>
            </ol>

            <h4 class="text-uppercase font-weight-bold">II. Sobre las Responsabilidades del Usuario</h4>
            <ol>
                <li>El usuario será responsable de los daños y perjuicios producidos o que pudieran producirse en el
                    futuro, que se deriven del incumplimiento de las condiciones de uso del servicio.</li>
                <li>El usuario debe abstenerse de realizar actos que atenten contra el sitio WEB, o que de alguna forma
                    puedan dañar, inutilizar, sobrecargar, deteriorar, impedir o limitar la utilización de todas o
                    algunas de sus funcionalidades. Es responsabilidad de los usuarios prevenir y eliminar cualquier
                    evento de carácter técnico, o de otra naturaleza que pueda dificultar el uso del presente servicio.
                </li>
                <ul>
                    <li>Comprobar el correcto funcionamiento de la configuración de sus computadoras.</li>
                    <li>Verificar la disponibilidad y configuración de sus enlaces.</li>
                    <li>Asegurar la calidad de sus conexiones a Internet.</li>
                </ul>
            </ol>

            <h4 class="text-uppercase font-weight-bold">III. Declaración</h4>
            <p>El Poder Judicial podrá modificar, en cualquier momento, los presentes términos y condiciones de uso, en
                todo o parte; circunstancia que los usuarios declaran conocer y aceptar. El servicio de emisión de
                Certificado Electrónico de Antecedentes Disciplinarios y el Certificado Electrónico de Expedientes, ha
                adoptado los niveles de seguridad de protección de los datos personales requeridos, instalando las
                medidas técnicas y legales necesarias para evitar la pérdida, mal uso, alteración, acceso no autorizado
                y robo de los datos facilitados.</p>

        </div>
        <div class="pt-4 d-flex flex-column form-group">
            <div class="d-flex flex-row">
                <input class="form-control btn-small" type="checkbox" id="cbTerminos" name="cbTerminos" value="0"
                    style="width:20px; height:20px;">
                <label for="cbTerminos" class="pl-2"> He leído y acepto los Términos Legales y Condiciones de uso de la
                    Autoridad Nacional de Control</label><br>

            </div>

        </div>
        <div class="text-center pt-5">
            <button class="btn btn-main" name="submit" type="submit">Aceptar</button>
            <a class="btn btn-light" href="@Url.Action("Salir", "Home")">
                Salir
            </a>
        </div>

    </form>
</div>



<!-- Modal -->
<div class="modal fade" id="InformacionModalCenter" role="dialog" data-backdrop="static" data-keyboard="false"
    tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header  btn-main">
                <h5 class="modal-title" id="exampleModalLongTitle" style="color:#fff">Importante</h5>

            </div>
            <div class="modal-body">
                <div>
                    <span>
                        Estimado usuario, si desea tramitar sus Certificados de Antecedentes Disciplinarios y/o
                        Certificado de Expedientes electrónicos tenga en cuenta la siguiente información:
                    </span>
                    <ul>
                        <li>
                            Los Certificados de Antecedentes Disciplinarios y/o Certificado de Expedientes electrónico
                            (SIDI) son válidos para su uso nacional.
                        </li>
                        <li>
                            Los Certificados de Antecedentes Disciplinarios y/o Certificado de Expedientes electrónico
                            (SIDI) son documentos en formato PDF firmado digitalmente por el Poder Judicial.
                        </li>
                        <li>
                            El trámite de los Certificado de Antecedentes Disciplinarios y/o Certificado de Expedientes
                            electrónico (SIDI) es estrictamente personal en cumplimiento a lo dispuesto en la Ley N.°
                            29733, Ley de Protección de Datos Personales.
                        </li>
                        <li>
                            Si el registro o trámite fuera observado significa que existen datos que deben verificarse
                            previamente; por lo que se realizará un proceso de revisión, el tiempo de espera es en
                            promedio de 24 horas.
                        </li>
                        <li>
                            Si el trámite del Certificado Antecedentes Disciplinarios y/o Certificado de Expedientes
                            electrónico (SIDI) se realiza fuera del horario laboral y este resultara “Observado”, el
                            proceso de trámite se atenderá al siguiente día hábil.
                        </li>
                        <li>
                            El Certificado Antecedentes Disciplinarios y/o Certificado de Expedientes electrónico (SIDI)
                            tiene una vigencia de 90 días calendarios, período en cual podrá ser utilizado.
                        </li>

                    </ul>
                    <span class="text-justify"> <strong>Nota:</strong> Las precisiones brindadas en esta ventana solo
                        aplican para los trámites realizados en esta plataforma.</span>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-main" data-dismiss="modal">Aceptar</button>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#InformacionModalCenter').modal('toggle');


            $('#terminosCondiciones-form').bootstrapValidator({
                fields: {
                    cbTerminos: {
                        validators: {
                            notEmpty: {
                                message: 'Debes aceptar los términos y condiciones para continuar'
                            }
                        }
                    }
                }
            }).on('success.form.bv', function (e) {
                // Detén el envío del formulario
                e.preventDefault();
                var urlDestino = '@Url.Action("Index", "Autenticacion")';

                // Realiza la redirección después de la validación del formulario
                window.location.href = urlDestino;

            });
        });



    </script>
}